[package]
name = "req-enc-dec-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "req_enc_dec_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
openssl = "0.10"
base64 = "0.21"
sha2 = "0.10"
hex = "0.4"

